resources:
- resourceName: elasticsearch
  deploymentTemplate: |-
    apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
     name: elasticsearch
     namespace: "{{.Namespace}}"
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
          ports:
          - containerPort: 7200
          env:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  serviceTemplate: |-
    apiVersion: v1
    kind: Service
    metadata:
    labels:
        app: elasticsearch
    name: elasticsearch
    namespace: {service_namespace}
    annotations:
        "consul.hashicorp.com/service-sync": "true"
        "consul.hashicorp.com/service-name": "{service_namespace}"
        "consul.hashicorp.com/service-tags": "nocheck,http"
        "consul.hashicorp.com/service-meta-OWNER": nosql
        "consul.hashicorp.com/service-meta-REQUESTER": {owner}
        "consul.hashicorp.com/service-meta-ttl": {ttl}
    spec:
    externalTrafficPolicy: Local
    ports:
    - name: elasticsearch
        nodePort: {attributed_port}
        port: {attributed_port}
        protocol: TCP
        targetPort: 9090
    selector:
        app: elasticsearch
    sessionAffinity: None
    type: NodePort
    status:
    loadBalancer: {}