resources:
- resourceName: elasticsearch
  deploymentTemplate: |-
    apiVersion: apps/v1beta1
    kind: Deployment
    metadata: 
        name: elasticsearch
        namespace: "{{.Namespace}}"
    spec:
        selector:
            matchLabels:
                app: elasticsearch
        replicas: 1
        template:
            metadata:
                labels:
                    app: elasticsearch
            spec:
                initContainers:
                - name: init-sysctl
                    image: busybox:1.27.2
                    command:
                    - sysctl
                    - -w
                    - vm.max_map_count=262144
                    securityContext:
                    privileged: true
                containers: 
                - name: elasticsearch
                  image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
                  env:
                  - name: "ES_JAVA_OPTS"
                    value: "-Xms512m -Xmx512m"
                  ports: 
                  - containerPort: 7200
  serviceTemplate: |-
    apiVersion: v1
    kind: Service
    metadata:
        labels:
            app: elasticsearch
        name: elasticsearch
        namespace: "{{.Namespace}}"
        annotations:
            "consul.hashicorp.com/service-sync": "true"
            "consul.hashicorp.com/service-name": "{{.Namespace}}"
            "consul.hashicorp.com/service-tags": "nocheck,http"
            "consul.hashicorp.com/service-meta-OWNER": nosql
            "consul.hashicorp.com/service-meta-REQUESTER": test
            "consul.hashicorp.com/service-meta-ttl": test
    spec:
        externalTrafficPolicy: Local
        ports:
        - name: elasticsearch
            protocol: TCP
            port: 7200
            targetPort: 7200
        selector:
            app: elasticsearch
        sessionAffinity: None
        type: NodePort