resources:
- resourceName: elasticsearch
  durationDefault: "5m"
  deploymentTemplate: |-
    apiVersion: apps/v1beta1
    kind: Deployment
    metadata: 
        name: elasticsearch
        namespace: "{{.Namespace}}"
    spec:
        selector:
            matchLabels:
                app: elasticsearch
        replicas: 1
        template:
            metadata:
                labels:
                    app: elasticsearch
            spec:
                initContainers:
                - name: init-sysctl
                  image: busybox:1.27.2
                  command:
                  - sysctl
                  - -w
                  - vm.max_map_count=262144
                  securityContext:
                    privileged: true
                containers: 
                - name: elasticsearch
                  image: "docker.elastic.co/elasticsearch/elasticsearch:7.3.0"
                  env:
                  - name: "discovery.type"
                    value: "single-node"
                  - name: NUMBER_OF_MASTERS
                    value: "1"
                  - name: NODE_MASTER
                    value: "true"
                  - name: NODE_INGEST
                    value: "true"
                  - name: NODE_DATA
                    value: "true"
                  - name: HTTP_ENABLE
                    value: "true"

                  ports: 
                  - containerPort: 9200
  serviceTemplate: |-
    apiVersion: v1
    kind: Service
    metadata:
        labels:
            app: elasticsearch
        name: elasticsearch
        namespace: "{{.Namespace}}"
        annotations:
            "consul.hashicorp.com/service-sync": "true"
            "consul.hashicorp.com/service-name": "kubernetes-{{.Namespace}}"
            "consul.hashicorp.com/service-tags": "nocheck,http"
            "consul.hashicorp.com/service-meta-REQUESTER": "{{.Owner}}"
            "consul.hashicorp.com/service-meta-experiration-date": "{{.ExpirationDate}}"
    spec:
        externalTrafficPolicy: Local
        ports:
        - name: elasticsearch
          protocol: TCP
          port: 9200
          targetPort: 9200
        selector:
            app: elasticsearch
        sessionAffinity: None
        type: NodePort