apiVersion: v1
kind: Service
metadata:
  labels:
      app: elasticsearch
  name: elasticsearch
  namespace: ephem-elasticsearch-dybvrx7lexvfvqruq4par5
  annotations:
      "consul.hashicorp.com/service-sync": "true"
      "consul.hashicorp.com/service-name": "ephem-elasticsearch-dybvrx7lexvfvqruq4par5"
      "consul.hashicorp.com/service-tags": "nocheck,http"
      "consul.hashicorp.com/service-meta-OWNER": nosql
      "consul.hashicorp.com/service-meta-REQUESTER": test
      "consul.hashicorp.com/service-meta-ttl": test
spec:
  externalTrafficPolicy: Local
  ports:
  - name: elasticsearch
    protocol: TCP
    port: 7200
    targetPort: 7200
  selector:
    app: elasticsearch
  sessionAffinity: None
  type: NodePort